language: python
python:
- '3.8'
install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install Pillow
- pip install requests
script: pytest
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  file: "$TRAVIS_BUILD_DIR/MyStory.apk"
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  overwrite: true
  on:
    branch: master
    tag: true