language: python
python:
  - "3.8"

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install Pillow
  - pip install requests
script: pytest
deploy:
  provider: releases
  file: $TRAVIS_BUILD_DIR/MyStory.apk
  api_key: e691951ba34c01295e9cfc6f442ac1ff8588abf0
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true