language: python
python:
- '3.8'
install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install Pillow
- pip install requests
script: pytest
deploy:
  provider: releases
  api_key: "995a2209f13cb59873aa05fd3cf853d7bf6aee83"
  file: "./MyStory.apk"
  skip_cleanup: true
  draft: true
  name: dev-build-$TRAVIS_TAG
  overwrite: true
  target_commitish: "$TRAVIS_COMMIT"
  on:
    repo: cs130-w21/6
    tag: true
env:
  global:
    secure: 995a2209f13cb59873aa05fd3cf853d7bf6aee83
