language: python
python:
- '3.8'
install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install Pillow
- pip install requests
script: pytest
deploy:
  provider: mystory
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  file: "./MyStory.apk"
  overwrite: true
  on:
    repo: cs130-w21/6